config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :posts


end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs

  has_many :subs,
  through: :post_subs,
  source: :sub




end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub_id, :post_id, presence: true
  validates :sub_id, uniqueness: { scope: :post_id }

  belongs_to :sub

  belongs_to :post
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs

  has_many :posts,
  through: :post_subs,
  source: :post

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Sub

  has_many :posts,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: :Post

  attr_reader :password

  def self.find_by_credentials(user_name, pw)
    user = User.find_by(username: user_name)
    return user if user && user.is_password?(pw)
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(32)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(32)
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    pw_digest = BCrypt::Password.new(self.password_digest)
    pw_digest.is_password?(pw)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def required_log_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_if_author, only: :edit

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save!
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id) unless sub_id == ""
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      redirect_to sub_url(subtopic)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to sub_url(subtopic)
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      @post.subs.each do |post_sb|
        unless params[:post][:sub_ids].include?(post_sb.id)
          PostSub.find_by(sub_id: post_sb.id, post_id: @post.id).destroy
        end

        params[:post][:sub_ids].each do |param_sub_id|
           PostSub.create(post_id: @post.id, sub_id: param_sub_id) unless param_sub_id == ""
        end

      end

      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end


  def check_if_author
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      redirect_to post_url(@post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.new(
    username: params[:user][:username],
    password: params[:user][:password]
    )

    if @user.save!
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid name or password!"]
      render :new
    end
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :check_if_moderator, only: [:edit]

  def index
    @subs = Sub.all
    render :index
  end

  def new

  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end

  end

  def show
    @sub = Sub.find_by_id(params[:id])
    render :show
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end


  end

  def edit
    @sub = Sub.find(params[:id])

    if @sub.nil?
      flash[:errors] = ["You are not the moderator and cannot edit this sub!"]
      redirect_to subs_url
    else
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find(params[:id])
    @sub.destroy
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def check_if_moderator
    @sub = Sub.find(params[:id])
    if current_user.nil? || !(current_user.id == @sub.user_id)
      redirect_to new_session_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\"
    name=\"authenticity_token\"
    value=\"#{form_authenticity_token}\" />".html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<form action="<%= post_url(id: @post.id) %>" method="post">
<%= auth_token %>
  <input type="hidden" name="_method" value="patch" />
  <h2> <%= "Edit #{@post.title}'s content/URL:"  %></h2>

  <label> Content:
    <input type="text" name="post[content]"/>
  </label>

  <label> URL:
    <input type="text" name="post[content]"/>
  </label>

  <label>Subs</label>

 <input type="hidden" name="post[sub_ids][]" value="">

 <% Sub.all.each do |sb| %>
   <label><%= sb.title %>
     <input type="checkbox"
             value="<%= sb.id %>"
             name="post[sub_ids][]"
             <%= "checked" if @post.subs.include?(sb) %>>
   </label>
 <% end %>

  <input type="submit" value="Update Post!" />

</form>

app/views/posts/new.html.erb
<form action="<%=posts_url%>" method="post">
  <%= auth_token %>
  <label> Title:
    <input type="text" name="post[title]"/>
  </label>

  <label> Content:
    <input type="text" name="post[content]"/>
  </label>

  <label> Link's Url:
    <input type="text" name="post[url]"/>
  </label>

  <label>Subs</label>

 <input type="hidden" name="post[sub_ids][]" value="">

 <% Sub.all.each do |sb| %>
   <label><%= sb.title %>
     <input type="checkbox"
             value="<%= sb.id %>"
             name="post[sub_ids][]"
             <%= "checked" if @post.subs.include?(sb) %>>
   </label>
 <% end %>

  <%= button_to "Create Post!", posts_url, method: :post %>

</form>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<section>
<%= @post.content %>
<%= @post.url %>
</section>

<%= link_to "Edit #{@post.title }?", edit_post_url, method: :get %>

app/views/subs/edit.html.erb
<form action="<%= sub_url(@sub) %>" method="post">
<%= auth_token %>
  <input type="hidden" name="_method" value="patch" />
  <h2> <%= "Edit #{@sub.title}:"  %></h2>

  <label> Title:
    <input type="text" name="sub[title]"/>
  </label>

  <label> Description:
    <textarea name="sub[description]"> <%= @sub.description%> </textarea>
  </label>

  <input type="submit" value="Update Sub!" />

</form>

app/views/subs/index.html.erb
<h2>The Subtopics Are:</h2>

<section>
  <%= link_to "Create New Sub!", new_sub_url, method: :get %>
</section>

<ul>
  <% @subs.each do |subtopic| %>
    <li>
      <%=  link_to subtopic.title, sub_url(subtopic), method: :get%>
      <br />
      <%=  subtopic.description %>
    </li>
  <% end  %>
</ul>

app/views/subs/new.html.erb
<form action="/subs" method="post">
  <label> Title:
    <input type="text" name="sub[title]"/>
  </label>
  <label> Description:
    <input type="text" name="sub[description]"/>
  </label>

  <%= button_to "Create Sub!", subs_url, method: :post %>

</form>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<section>
<%= @sub.description %>
</section>

<%= link_to "Edit #{@sub.title }?", edit_sub_url, method: :get %>
<%= link_to "Create a Post!", new_post_url%>

<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post_url(post) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<form action="/users" method="post">
  <label> Username:
    <input type="text" name="user[username]"/>
  </label>
  <label> Password:
    <input type="text" name="user[password]"/>
  </label>

  <%= button_to "Submit", users_url, method: :post %>

</form>

app/views/users/show.html.erb
<h2><%= current_user.username %></h2>